In [1]:
!pip install arithmetic_compressor

In [28]:
import numpy as np
from arithmetic_compressor import AECompressor
from arithmetic_compressor.models import StaticModel

# create the model
model = StaticModel({'0': 0.65, '1': 0.35})

# create an arithmetic coder
coder = AECompressor(model)

# encode some data
data = "000000"

# Compress, convert to string
compressed = coder.compress(data)
compressed_str = "".join([str(s) for s in coder.compress(data)])

# Decompress
N = len(data)
decoded = coder.decompress(compressed, N)
decoded_str = "".join([str(s) for s in coder.decompress(compressed, N)])

print(f"Data: ({len(data)}): {data}")
print(f"Compressed ({len(compressed_str)}): {compressed_str}")
print(f"Decoded ({len(decoded_str)}): {decoded_str}")
print(f"Compression ratio: {len(data) / len(compressed):.2f}")

Data: (6): 000000
Compressed (4): 0001
Decoded (6): 000000
Compression ratio: 1.50


In [29]:
import torch
import torch.nn as nn
import torch.optim as optim

import torch.nn as nn

class BasicLSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, fixed_value=0.1):
        super(BasicLSTM, self).__init__()

        self.lstm = nn.LSTM(input_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.softmax = nn.Softmax(dim=1)

        # Setting fixed initial values for weights and biases
        with torch.no_grad():
            # For LSTM layer
            self.lstm.weight_ih_l0.fill_(fixed_value)
            self.lstm.weight_hh_l0.fill_(fixed_value)
            self.lstm.bias_ih_l0.fill_(fixed_value)
            self.lstm.bias_hh_l0.fill_(fixed_value)

            # For FC layer
            self.fc.weight.fill_(fixed_value)
            self.fc.bias.fill_(fixed_value)

    def forward(self, x):
        h0 = torch.zeros(1, x.size(0), self.lstm.hidden_size)
        c0 = torch.zeros(1, x.size(0), self.lstm.hidden_size)
        
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        out = self.softmax(out)
        return out

In [30]:
# Load the file into a PyTorch tensor
dataset = []
with open("data.txt", 'r') as in_file:
    for line in in_file:
        tensor_representation = torch.tensor([int(bit) for bit in line.strip()], dtype=torch.int)
        dataset.append(tensor_representation)

dataset[0:4]

[tensor([0, 0, 0, 0, 0, 0], dtype=torch.int32),
 tensor([0, 0, 0, 0, 0, 1], dtype=torch.int32),
 tensor([0, 0, 0, 0, 1, 0], dtype=torch.int32),
 tensor([0, 0, 0, 0, 1, 1], dtype=torch.int32)]

In [31]:
# Data we want to compress
sample = dataset[0]
max_sentence_len = len(sample)

# Network hyperparameters
input_dim = max_sentence_len  # Max length of sentence (5 tokens)
num_layers = 1 # One layer LSTM
hidden_dim = 5 # Hidden dimension
output_dim = 2 # since we have two possible outputs: 0 and 1
learning_rate = 5e-01 # Learning rate

# Create the LSTM model and optimizer
lstm_model = BasicLSTM(input_dim, hidden_dim, output_dim)
optimizer = optim.SGD(lstm_model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

# Test that it works
t = torch.Tensor([-1] * input_dim).view(1,1,-1)
print(f"Input: {t}")
print(f"Output: {lstm_model(t)}")

Input: tensor([[[-1., -1., -1., -1., -1., -1.]]])
Output: tensor([[0.5000, 0.5000]], grad_fn=<SoftmaxBackward0>)


In [32]:
lstm_model = BasicLSTM(input_dim, hidden_dim, output_dim, fixed_value=-0.1)
optimizer = optim.SGD(lstm_model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

# Prepare compressed text file
with open('compressed.txt', 'w') as file:
    # First sentence is actually not compressed
    compressed_str = "".join([str(s) for s in dataset[0].numpy()])
    file.write(f'{compressed_str}\n')

# Iterate over all sentences in dataset
for i2, sentence in enumerate(dataset):

    # We don't want to train on the last sentence, as we will already have compressed
    if i2 == len(dataset)-1:
        break
    
    # Input tensor starts with -1 (missing) for all (6) positions
    # Gets filled one by one as we progress through the sentence
    input_tensor = torch.Tensor([-1]*max_sentence_len).view(1, 1, -1)

    for i, bit in enumerate(sentence):
        if i == len(sentence)-1:
            break

        # Input is all tokens so far
        input_tensor[0, 0, i] = sentence[i].view(1, 1, 1)

        # Next token to predict
        target_tensor = sentence[i+1].view(1).long()
        
        # Forward pass
        output = lstm_model(input_tensor)
        loss = criterion(output, target_tensor)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Print stats for first 10 iterations
        if i < 6 and i2 < 3:
            print(f"Input: {input_tensor}")
            print(f"Output: {output.detach().numpy()} (probability distribution))")
            print(f"Target: {target_tensor.detach().numpy()}, Predicted {np.argmax(output.detach().numpy())}\n")

    # After training on sentence, we compress it with the learned probability distribution
    prob_distribution = {
        0: output[0, 0].item(), # Learned probability for 0
        1: output[0, 1].item() # Learned probability for 1
        }

    model = StaticModel(prob_distribution)
    coder = AECompressor(model)

    next_sentence = dataset[i2+1].numpy().tolist()
    compressed = coder.compress(next_sentence)
    compressed_str = ''.join([str(i) for i in compressed])
    orig_str = "".join([str(s) for s in sentence.numpy()])

    with open('compressed.txt', 'a') as file:
        file.write(f'{compressed_str}\n')

    print(f"Original sentence: {orig_str}")
    print(f"Compessed sentence: {compressed_str}")
    print(f"Compression ratio: {len(orig_str)/len(compressed_str)}\n")

Input: tensor([[[ 0., -1., -1., -1., -1., -1.]]])
Output: [[0.5 0.5]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0., -1., -1., -1., -1.]]])
Output: [[0.56391734 0.43608257]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0., -1., -1., -1.]]])
Output: [[0.6190611 0.3809389]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0.,  0., -1., -1.]]])
Output: [[0.66563267 0.33436733]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0.,  0.,  0., -1.]]])
Output: [[0.7046688  0.29533118]] (probability distribution))
Target: [0], Predicted 0

Original sentence: 000000
Compessed sentence: 001
Compression ratio: 2.0

Input: tensor([[[ 0., -1., -1., -1., -1., -1.]]])
Output: [[0.74277276 0.25722724]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0., -1., -1., -1., -1.]]])
Output: [[0.769207   0.23079298]] (probability distribution))
Ta

In [33]:
# Load the compressed dataset into a PyTorch tensor
compressed_dataset = []
with open("compressed.txt", 'r') as in_file:
    for line in in_file:
        tensor_representation = torch.tensor([int(bit) for bit in line.strip()], dtype=torch.int)
        compressed_dataset.append(tensor_representation)

compressed_dataset[0:4]

[tensor([0, 0, 0, 0, 0, 0], dtype=torch.int32),
 tensor([0, 0, 1], dtype=torch.int32),
 tensor([0, 1, 1, 1], dtype=torch.int32),
 tensor([0, 1, 1, 0, 1, 1, 1], dtype=torch.int32)]

In [34]:
# Initialize new LSTM model, but with fixed weights same as before
# NB: No weights are loaded - we will learn them as we decompress

lstm_model = BasicLSTM(input_dim, hidden_dim, output_dim, fixed_value=-0.1)
optimizer = optim.SGD(lstm_model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

# Prepare compressed text file
with open('decompressed.txt', 'w') as file:
    # First sentence is actually not compressed
    compressed_str = "".join([str(s) for s in dataset[0].numpy()])
    file.write(f'{compressed_str}\n')

# Nb: First sentence is not compressed!
decompressed_dataset = []
decompressed_dataset.append(compressed_dataset[0])

# Iterate over all sentences in dataset. Note that first sentence is uncompressed
for i2, _ in enumerate(compressed_dataset):

    # Grab last decompressed sentence
    sentence = decompressed_dataset[-1]
    
    # Input tensor starts with -1 (missing) for all (6) positions
    # Gets filled one by one as we progress through the sentence
    input_tensor = torch.Tensor([-1]*max_sentence_len).view(1, 1, -1)

    if i2 == len(compressed_dataset)-2:
        break

    for i, bit in enumerate(sentence):

        if i == len(sentence)-1:
            break

        # Input is all tokens so far
        input_tensor[0, 0, i] = sentence[i].view(1, 1, 1)

        # Next token to predict
        target_tensor = sentence[i+1].view(1).long()
        
        # Forward pass
        output = lstm_model(input_tensor)
        loss = criterion(output, target_tensor)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Print stats for first 10 iterations
        if i < 7 and i2 < 3:
            print(f"Input: {input_tensor}")
            print(f"Output: {output.detach().numpy()} (probability distribution))")
            print(f"Target: {target_tensor.detach().numpy()}, Predicted {np.argmax(output.detach().numpy())}\n")

    # After training on sentence, we used learned probability distribution to decompress the next one!
    prob_distribution = {
        0: output[0, 0].item(), # Learned probability for 0
        1: output[0, 1].item() # Learned probability for 1
        }

    model = StaticModel(prob_distribution)
    coder = AECompressor(model)

    # Decompress next sentence
    next_comp_sentence = compressed_dataset[i2+1].numpy().tolist()
    decoded = coder.decompress(next_comp_sentence, max_sentence_len)
    decoded_str = "".join([str(s) for s in decoded])

    # Add decoded sentence to decompressed dataset
    decompressed_dataset.append(torch.Tensor(decoded))

    # Write to file
    with open('decompressed.txt', 'a') as file:
        file.write(f'{decoded_str}\n')    

    if i2 < 10:
        compressed_str = "".join([str(s) for s in next_comp_sentence])
        orig_str = "".join([str(s) for s in dataset[i2+1].numpy()])
        print(f"Original sentence: {orig_str}")
        print(f"Compressed sentence: {compressed_str}")
        print(f"Decoded sentence: {decoded_str}\n")

Input: tensor([[[ 0., -1., -1., -1., -1., -1.]]])
Output: [[0.5 0.5]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0., -1., -1., -1., -1.]]])
Output: [[0.56391734 0.43608257]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0., -1., -1., -1.]]])
Output: [[0.6190611 0.3809389]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0.,  0., -1., -1.]]])
Output: [[0.66563267 0.33436733]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0.,  0.,  0.,  0., -1.]]])
Output: [[0.7046688  0.29533118]] (probability distribution))
Target: [0], Predicted 0

Original sentence: 000001
Compressed sentence: 001
Decoded sentence: 000001

Input: tensor([[[ 0., -1., -1., -1., -1., -1.]]])
Output: [[0.74277276 0.25722724]] (probability distribution))
Target: [0], Predicted 0

Input: tensor([[[ 0.,  0., -1., -1., -1., -1.]]])
Output: [[0.769207   0.23079298]] (probability distribution))